/// Flutter icons VetAppIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VetAppIcons
///      fonts:
///       - asset: fonts/VetAppIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class VetAppIcons {
  VetAppIcons._();

  static const _kFontFam = 'VetAppIcons';

  static const IconData error = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData add2 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData alert = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData alert2 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData call = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData clinic = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData email = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData habitad = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData history = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData huella = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData peso = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData save = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData sexo = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData size = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData specie = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData stadistic = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData start = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe819, fontFamily: _kFontFam);
}
